# Generated by Django 5.1.15 on 2026-05-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="transcript",
            field=models.TextField(blank=True, default=""),
        ),
    ]
